import { DEFAULT_PLAN_MODULES } from "./constants"
import type {
  AdminNote,
  AuditEvent,
  HostelSubscription,
  Invoice,
  PaymentProof,
  PendingRequest,
  RequestedByDesignation,
} from "./types"
import { billedRateFor, calcARR } from "./utils"

const ev = (
  id: string,
  description: string,
  timestamp: string,
  adminName = "Akshay Sharma"
): AuditEvent => ({ id, description, timestamp, adminName })

const inv = (partial: Omit<Invoice, "invoiceType"> & { invoiceType?: Invoice["invoiceType"] }): Invoice => ({
  invoiceType: "annual_subscription",
  ...partial,
})

const note = (id: string, text: string, timestamp: string, adminName = "Akshay Sharma"): AdminNote => ({
  id,
  text,
  timestamp,
  adminName,
})

const proof = (partial: PaymentProof): PaymentProof => partial

const DESIGNATIONS: RequestedByDesignation[] = ["Warden", "Caretaker", "Student", "Parent"]
let designationCursor = 0
let requestSerialCursor = 0

const req = (
  partial: Omit<PendingRequest, "requestedByDesignation" | "requestNo"> & {
    requestedByDesignation?: RequestedByDesignation
    requestNo?: string
  }
): PendingRequest => {
  requestSerialCursor += 1
  return {
    requestNo: partial.requestNo ?? `UR-${String(requestSerialCursor).padStart(4, "0")}`,
    requestedByDesignation: DESIGNATIONS[designationCursor++ % DESIGNATIONS.length],
    ...partial,
  }
}

function hostel(
  row: Omit<HostelSubscription, "annualValue" | "_id" | "activatedStudentCount" | "addedStudentCount" | "contractRate"> & {
    _id?: string
    activatedStudentCount?: number
    addedStudentCount?: number
    contractRate?: number
  }
): HostelSubscription {
  const rate = row.status === "trial" ? 0 : billedRateFor(row.plan ?? null, row.activeModules)
  const contractRate = row.contractRate ?? rate
  const existingRequest = row.pendingRequests.find((request) => request.requestNo)
  const createdRequests: PendingRequest[] = []
  const invoices = row.invoices.map((invoice) => {
    let linkedRequest = existingRequest
    if (invoice.invoiceType !== "manual" && !invoice.upgradeRequestNo && !existingRequest) {
      linkedRequest = req({
        id: `pr-${invoice.id}`,
        type: "new_subscription",
        requestedBy: row.adminName,
        submittedOn: invoice.dateGenerated,
        status: "approved",
        planRequested: invoice.plan,
        studentCount: invoice.students,
        billingCycle: invoice.billingCycle ?? row.billingCycle,
        subscriptionStartDate: invoice.billingPeriodStart,
        renewalDate: invoice.billingPeriodEnd,
        details: `Subscription invoice ${invoice.invoiceNo}`,
      })
      createdRequests.push(linkedRequest)
    }
    const withCycle = {
      ...invoice,
      billingCycle: invoice.billingCycle ?? row.billingCycle,
      ...(invoice.invoiceType !== "manual" && linkedRequest && !invoice.upgradeRequestNo
        ? { upgradeRequestId: invoice.upgradeRequestId ?? linkedRequest.id, upgradeRequestNo: linkedRequest.requestNo }
        : {}),
    }
    return invoice.invoiceType === "annual_subscription"
      ? {
          ...withCycle,
          billingPeriodStart: row.subscriptionStartDate,
          billingPeriodEnd: row.renewalDate,
        }
      : withCycle
  })
  return {
    ...row,
    _id: row._id ?? row.hostelId,
    activatedStudentCount: row.activatedStudentCount ?? row.studentCount,
    addedStudentCount: row.addedStudentCount ?? 0,
    contractRate,
    annualValue: calcARR(row.studentCount, contractRate, row.status),
    pendingRequests: [...row.pendingRequests, ...createdRequests],
    invoices,
  }
}

export const INITIAL_HOSTELS: HostelSubscription[] = [
  hostel({
    hostelId: "h1",
    hostelCode: "YS-PUN-001",
    name: "Sunrise Boys Hostel",
    city: "Pune",
    state: "Maharashtra",
    adminName: "Rahul Deshmukh",
    adminPhone: "+91 98765 11101",
    plan: "PREMIUM",
    status: "active",
    billingCycle: "ANNUAL",
    studentCount: 180,
    subscriptionStartDate: "2026-08-01",
    renewalDate: "2027-08-01",
    lastPaymentDate: "2025-08-04",
    activeModules: [...DEFAULT_PLAN_MODULES.PREMIUM],
    pendingRequests: [
      req({
        id: "pr-h1-1",
        type: "plan_upgrade",
        requestedBy: "Rahul Deshmukh",
        submittedOn: "2026-08-28",
        status: "pending",
        planRequested: "ADVANCED",
        studentCount: 180,
        details: "Wants visitor logs and meal tracking before the new semester.",
      }),
      req({
        id: "pr-h1-2",
        type: "student_count_update",
        requestedBy: "Rahul Deshmukh",
        submittedOn: "2026-09-02",
        status: "pending",
        studentCount: 195,
        requestedAddStudents: 15,
        details: "15 extra beds confirmed for the incoming batch.",
      }),
      req({
        id: "pr-h1-3",
        type: "module_add_remove",
        requestedBy: "Rahul Deshmukh",
        submittedOn: "2026-09-04",
        status: "pending",
        modules: ["VISITOR", "LAUNDRY"],
        details: "Need visitor logs and laundry before parent weekend.",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h1-1",
        invoiceNo: "yoco/inv/2025-26/0002",
        billingPeriodStart: "2025-08-01",
        billingPeriodEnd: "2026-07-31",
        students: 180,
        amount: 108000,
        gst: 19440,
        total: 127440,
        status: "paid",
        dateGenerated: "2025-07-20",
        sameState: true,
        dueDate: "2025-08-05",
        modules: [...DEFAULT_PLAN_MODULES.PREMIUM],
        plan: "PREMIUM",
        rate: 50,
      }),
    ],
    paymentProofs: [
      proof({
        id: "pp-h1-1",
        fileName: "sunrise-neft-aug2025.pdf",
        uploadedOn: "2025-08-04",
        uploadedBy: "Rahul Deshmukh",
        forPeriod: "Aug 2025 – Jul 2026",
      }),
    ],
    auditTrail: [
      ev("a-h1-2", "Invoice yoco/inv/2025-26/0002 generated", "2025-07-20T10:12:00", "System"),
      ev("a-h1-1", "Premium plan activated", "2025-08-01T09:00:00"),
    ],
    notes: [
      note("n-h1-1", "Owner prefers annual billing. Confirmed GSTIN on file.", "2025-08-02T11:20:00"),
    ],
  }),
  hostel({
    hostelId: "h2",
    hostelCode: "YS-BLR-014",
    name: "Lakeview Girls",
    city: "Bengaluru",
    state: "Karnataka",
    adminName: "Priya Nair",
    adminPhone: "+91 98450 22110",
    plan: "ADVANCED",
    status: "active",
    billingCycle: "SEMIANNUAL",
    studentCount: 240,
    subscriptionStartDate: "2025-09-01",
    renewalDate: "2026-03-01",
    lastPaymentDate: "2025-09-03",
    activeModules: [...DEFAULT_PLAN_MODULES.ADVANCED],
    pendingRequests: [],
    invoices: [
      inv({
        id: "inv-h2-1",
        invoiceNo: "yoco/inv/2025-26/0003",
        billingPeriodStart: "2025-09-01",
        billingPeriodEnd: "2026-02-28",
        students: 240,
        amount: 86400,
        gst: 15552,
        total: 101952,
        status: "paid",
        dateGenerated: "2025-08-25",
        sameState: false,
        dueDate: "2025-09-10",
        modules: [...DEFAULT_PLAN_MODULES.ADVANCED],
        plan: "ADVANCED",
        rate: 60,
      }),
    ],
    paymentProofs: [
      proof({
        id: "pp-h2-1",
        fileName: "lakeview-upi-sep2025.jpg",
        uploadedOn: "2025-09-03",
        uploadedBy: "Priya Nair",
        forPeriod: "Sep 2025 – Feb 2026",
      }),
    ],
    auditTrail: [
      ev("a-h2-2", "Payment proof uploaded — lakeview-upi-sep2025.jpg", "2025-09-03T16:40:00", "Priya Nair"),
      ev("a-h2-1", "Advanced plan activated", "2025-09-01T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h3",
    hostelCode: "YS-JAI-007",
    name: "Heritage Co-Ed Stay",
    city: "Jaipur",
    state: "Rajasthan",
    adminName: "Aman Singh",
    adminPhone: "+91 94140 33021",
    plan: "ELITE",
    status: "active",
    billingCycle: "QUARTERLY",
    studentCount: 320,
    subscriptionStartDate: "2026-06-01",
    renewalDate: "2026-09-01",
    lastPaymentDate: "2026-06-02",
    activeModules: [...DEFAULT_PLAN_MODULES.ELITE],
    pendingRequests: [
      req({
        id: "pr-h3-1",
        type: "student_count_update",
        requestedBy: "Aman Singh",
        submittedOn: "2026-08-30",
        status: "pending",
        studentCount: 350,
        details: "Intake rising from 320 to 350 for the next quarter.",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h3-1",
        invoiceNo: "yoco/inv/2026-27/0001",
        billingPeriodStart: "2026-06-01",
        billingPeriodEnd: "2026-08-31",
        students: 320,
        amount: 89600,
        gst: 16128,
        total: 105728,
        status: "paid",
        dateGenerated: "2026-05-20",
        sameState: false,
        dueDate: "2026-06-05",
        modules: [...DEFAULT_PLAN_MODULES.ELITE],
        plan: "ELITE",
        rate: 70,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h3-2", "Invoice yoco/inv/2026-27/0001 marked as paid", "2026-06-02T12:00:00"),
      ev("a-h3-1", "Elite plan activated", "2026-06-01T09:00:00"),
    ],
    notes: [note("n-h3-1", "High-value account. Call before any plan change.", "2026-06-10T09:15:00")],
  }),
  hostel({
    hostelId: "h4",
    hostelCode: "YS-HYD-022",
    name: "Greenfield Hostel",
    city: "Hyderabad",
    state: "Telangana",
    adminName: "Sneha Reddy",
    adminPhone: "+91 90001 44550",
    plan: "PREMIUM",
    status: "active",
    billingCycle: "ANNUAL",
    studentCount: 95,
    subscriptionStartDate: "2026-01-15",
    renewalDate: "2027-01-15",
    lastPaymentDate: "2026-01-18",
    proRatedAdjustment: 7500,
    activeModules: [...DEFAULT_PLAN_MODULES.PREMIUM],
    pendingRequests: [],
    invoices: [
      inv({
        id: "inv-h4-1",
        invoiceNo: "yoco/inv/2025-26/0007",
        billingPeriodStart: "2026-01-15",
        billingPeriodEnd: "2027-01-14",
        students: 95,
        amount: 57000,
        gst: 10260,
        total: 67260,
        status: "paid",
        dateGenerated: "2026-01-10",
        sameState: false,
        dueDate: "2026-01-20",
        modules: [...DEFAULT_PLAN_MODULES.PREMIUM],
        plan: "PREMIUM",
        rate: 50,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h4-2", "Seat count updated 80 → 95", "2026-04-01T11:00:00"),
      ev("a-h4-1", "Premium plan activated", "2026-01-15T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h5",
    hostelCode: "YS-MUM-009",
    name: "Riverbank Residency",
    city: "Mumbai",
    state: "Maharashtra",
    adminName: "Neha Kulkarni",
    adminPhone: "+91 98200 77881",
    plan: "ADVANCED",
    status: "active",
    billingCycle: "ANNUAL",
    studentCount: 410,
    subscriptionStartDate: "2025-11-01",
    renewalDate: "2026-11-01",
    lastPaymentDate: "2025-11-05",
    activeModules: [...DEFAULT_PLAN_MODULES.ADVANCED],
    pendingRequests: [
      req({
        id: "pr-h5-1",
        type: "module_add_remove",
        requestedBy: "Neha Kulkarni",
        submittedOn: "2026-08-19",
        status: "pending",
        modules: ["LAUNDRY"],
        details: "Add Laundry module for the riverside wing.",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h5-1",
        invoiceNo: "yoco/inv/2025-26/0005",
        billingPeriodStart: "2025-11-01",
        billingPeriodEnd: "2026-10-31",
        students: 410,
        amount: 295200,
        gst: 53136,
        total: 348336,
        status: "paid",
        dateGenerated: "2025-10-20",
        sameState: true,
        dueDate: "2025-11-05",
        modules: [...DEFAULT_PLAN_MODULES.ADVANCED],
        plan: "ADVANCED",
        rate: 60,
      }),
    ],
    paymentProofs: [
      proof({
        id: "pp-h5-1",
        fileName: "riverbank-rtgs-nov2025.pdf",
        uploadedOn: "2025-11-05",
        uploadedBy: "Neha Kulkarni",
        forPeriod: "Nov 2025 – Oct 2026",
      }),
    ],
    auditTrail: [
      ev("a-h5-2", "WhatsApp sent — invoice_sent — 05 Nov 2025, 10:12", "2025-11-05T10:12:00"),
      ev("a-h5-1", "Advanced plan activated", "2025-11-01T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h6",
    hostelCode: "YS-DEL-031",
    name: "Campus Nest",
    city: "New Delhi",
    state: "Delhi",
    adminName: "Vikram Mehta",
    adminPhone: "+91 98100 55667",
    plan: "ELITE",
    status: "trial",
    billingCycle: "ANNUAL",
    studentCount: 150,
    subscriptionStartDate: "2026-08-10",
    renewalDate: "2026-09-09",
    activeModules: [...DEFAULT_PLAN_MODULES.ELITE],
    pendingRequests: [],
    invoices: [
      inv({
        id: "inv-h6-1",
        invoiceNo: "yoco/inv/2026-27/0003",
        billingPeriodStart: "2026-08-10",
        billingPeriodEnd: "2026-09-09",
        students: 150,
        amount: 0,
        gst: 0,
        total: 0,
        status: "paid",
        dateGenerated: "2026-08-10",
        sameState: false,
        dueDate: "2026-09-09",
        modules: [...DEFAULT_PLAN_MODULES.ELITE],
        plan: "ELITE",
        rate: 0,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h6-2", "Trial started — all modules unlocked, billing ₹0", "2026-08-10T09:00:00"),
      ev("a-h6-1", "Hostel onboarded", "2026-08-09T15:30:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h7",
    hostelCode: "YS-CHE-018",
    name: "Scholar's Court",
    city: "Chennai",
    state: "Tamil Nadu",
    adminName: "Lakshmi Iyer",
    adminPhone: "+91 94440 11223",
    plan: "PREMIUM",
    status: "trial",
    billingCycle: "ANNUAL",
    studentCount: 70,
    subscriptionStartDate: "2026-08-20",
    renewalDate: "2026-09-19",
    activeModules: [...DEFAULT_PLAN_MODULES.PREMIUM],
    pendingRequests: [
      req({
        id: "pr-h7-1",
        type: "plan_upgrade",
        requestedBy: "Lakshmi Iyer",
        submittedOn: "2026-08-27",
        status: "pending",
        planRequested: "ADVANCED",
        studentCount: 70,
        details: "Trial hostel wants to start on Advanced instead of Premium.",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h7-1",
        invoiceNo: "yoco/inv/2026-27/0004",
        billingPeriodStart: "2026-08-20",
        billingPeriodEnd: "2026-09-19",
        students: 70,
        amount: 0,
        gst: 0,
        total: 0,
        status: "unpaid",
        dateGenerated: "2026-08-20",
        sameState: false,
        dueDate: "2026-09-19",
        modules: [...DEFAULT_PLAN_MODULES.PREMIUM],
        plan: "PREMIUM",
        rate: 0,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h7-2", "Trial started — 30 days", "2026-08-20T09:00:00"),
      ev("a-h7-1", "Hostel onboarded", "2026-08-19T18:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h8",
    hostelCode: "YS-PUN-044",
    name: "Maple Leaf Hostel",
    city: "Pune",
    state: "Maharashtra",
    adminName: "Sagar Patil",
    adminPhone: "+91 98810 33445",
    plan: "ADVANCED",
    status: "expired",
    billingCycle: "ANNUAL",
    studentCount: 160,
    subscriptionStartDate: "2025-07-20",
    renewalDate: "2026-07-20",
    lastPaymentDate: "2025-07-22",
    lastContactedAt: "2026-08-22",
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.ADVANCED],
    pendingRequests: [],
    invoices: [
      inv({
        id: "inv-h8-1",
        invoiceNo: "yoco/inv/2025-26/0001",
        billingPeriodStart: "2025-07-20",
        billingPeriodEnd: "2026-07-19",
        students: 160,
        amount: 115200,
        gst: 20736,
        total: 135936,
        status: "paid",
        dateGenerated: "2025-07-10",
        sameState: true,
        dueDate: "2025-07-25",
        modules: [...DEFAULT_PLAN_MODULES.ADVANCED],
        plan: "ADVANCED",
        rate: 60,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h8-2", "Subscription expired", "2026-07-21T00:05:00", "System"),
      ev("a-h8-1", "Advanced plan activated", "2025-07-20T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h9",
    hostelCode: "YS-BLR-051",
    name: "Oakwood Stay",
    city: "Bengaluru",
    state: "Karnataka",
    adminName: "Ananya Rao",
    adminPhone: "+91 97311 66778",
    plan: "PREMIUM",
    status: "expired",
    billingCycle: "SEMIANNUAL",
    studentCount: 88,
    subscriptionStartDate: "2026-01-10",
    renewalDate: "2026-07-10",
    lastPaymentDate: "2026-01-12",
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.PREMIUM],
    pendingRequests: [
      req({
        id: "pr-h9-1",
        type: "renewal_after_expiry",
        requestedBy: "Ananya Rao",
        submittedOn: "2026-08-12",
        status: "pending",
        planRequested: "PREMIUM",
        studentCount: 88,
        details: "Bank is processing the overdue invoice — wants to renew Premium.",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h9-1",
        invoiceNo: "yoco/inv/2025-26/0006",
        billingPeriodStart: "2026-01-10",
        billingPeriodEnd: "2026-07-09",
        students: 88,
        amount: 26400,
        gst: 4752,
        total: 31152,
        status: "unpaid",
        dateGenerated: "2025-12-28",
        sameState: false,
        dueDate: "2026-01-15",
        modules: [...DEFAULT_PLAN_MODULES.PREMIUM],
        plan: "PREMIUM",
        rate: 50,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h9-2", "Subscription expired", "2026-07-11T00:05:00", "System"),
      ev("a-h9-1", "Premium plan activated", "2026-01-10T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h10",
    hostelCode: "YS-LKO-003",
    name: "Pearl Hostel",
    city: "Lucknow",
    state: "Uttar Pradesh",
    adminName: "Ritesh Verma",
    adminPhone: "+91 94150 88990",
    plan: "ELITE",
    status: "expired",
    billingCycle: "ANNUAL",
    studentCount: 200,
    subscriptionStartDate: "2024-06-01",
    renewalDate: "2025-06-01",
    lastPaymentDate: "2024-06-05",
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.ELITE],
    pendingRequests: [],
    invoices: [
      inv({
        id: "inv-h10-1",
        invoiceNo: "yoco/inv/2024-25/0001",
        billingPeriodStart: "2024-06-01",
        billingPeriodEnd: "2025-05-31",
        students: 200,
        amount: 168000,
        gst: 30240,
        total: 198240,
        status: "paid",
        dateGenerated: "2024-05-20",
        sameState: false,
        dueDate: "2024-06-10",
        modules: [...DEFAULT_PLAN_MODULES.ELITE],
        plan: "ELITE",
        rate: 70,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h10-2", "Modules locked — subscription expired", "2025-07-02T00:05:00", "System"),
      ev("a-h10-1", "Elite plan activated", "2024-06-01T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h11",
    hostelCode: "YS-IDR-012",
    name: "Silverline PG",
    city: "Indore",
    state: "Madhya Pradesh",
    adminName: "Kavita Joshi",
    adminPhone: "+91 98260 22334",
    plan: "ADVANCED",
    status: "expired",
    billingCycle: "QUARTERLY",
    studentCount: 54,
    subscriptionStartDate: "2025-10-01",
    renewalDate: "2026-01-01",
    lastPaymentDate: "2025-10-03",
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.ADVANCED],
    pendingRequests: [
      req({
        id: "pr-h11-1",
        type: "renewal_after_expiry",
        requestedBy: "Kavita Joshi",
        submittedOn: "2026-08-16",
        status: "on_hold",
        planRequested: "ADVANCED",
        studentCount: 54,
        details: "Wants to restart Advanced after lockout.",
        holdReason: "Previous quarter invoice still unpaid.",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h11-1",
        invoiceNo: "yoco/inv/2025-26/0004",
        billingPeriodStart: "2025-10-01",
        billingPeriodEnd: "2025-12-31",
        students: 54,
        amount: 12960,
        gst: 2333,
        total: 15293,
        status: "unpaid",
        dateGenerated: "2025-09-20",
        sameState: false,
        dueDate: "2025-10-10",
        modules: [...DEFAULT_PLAN_MODULES.ADVANCED],
        plan: "ADVANCED",
        rate: 60,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h11-2", "Modules locked — subscription expired", "2026-02-01T00:05:00", "System"),
      ev("a-h11-1", "Advanced plan activated", "2025-10-01T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h12",
    hostelCode: "YS-AMD-008",
    name: "Horizon Hostel",
    city: "Ahmedabad",
    state: "Gujarat",
    adminName: "Mehul Shah",
    adminPhone: "+91 98250 66771",
    plan: "PREMIUM",
    status: "expired",
    billingCycle: "ANNUAL",
    studentCount: 120,
    subscriptionStartDate: "2026-09-01",
    renewalDate: "2027-09-01",
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.PREMIUM],
    pendingRequests: [],
    invoices: [
      inv({
        id: "inv-h12-1",
        invoiceNo: "yoco/inv/2026-27/0005",
        billingPeriodStart: "2026-09-01",
        billingPeriodEnd: "2027-08-31",
        students: 120,
        amount: 72000,
        gst: 12960,
        total: 84960,
        status: "unpaid",
        dateGenerated: "2026-08-24",
        sameState: false,
        dueDate: "2026-09-10",
        modules: [...DEFAULT_PLAN_MODULES.PREMIUM],
        plan: "PREMIUM",
        rate: 50,
      }),
    ],
    paymentProofs: [
      proof({
        id: "pp-h12-1",
        fileName: "horizon-advance-aug2026.pdf",
        uploadedOn: "2026-08-24",
        uploadedBy: "Mehul Shah",
        forPeriod: "Sep 2026 – Aug 2027",
      }),
    ],
    auditTrail: [
      ev("a-h12-2", "Payment proof uploaded — horizon-advance-aug2026.pdf", "2026-08-24T14:10:00", "Mehul Shah"),
      ev("a-h12-1", "New subscription submitted — Premium", "2026-08-24T13:55:00", "Mehul Shah"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h13",
    hostelCode: "YS-COK-005",
    name: "Bluebell Stay",
    city: "Kochi",
    state: "Kerala",
    adminName: "Arun Menon",
    adminPhone: "+91 98470 44556",
    plan: "ADVANCED",
    status: "expired",
    billingCycle: "ANNUAL",
    studentCount: 210,
    subscriptionStartDate: "2026-09-15",
    renewalDate: "2027-09-15",
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.ADVANCED],
    pendingRequests: [
      req({
        id: "pr-h13-1",
        type: "new_subscription",
        requestedBy: "Arun Menon",
        submittedOn: "2026-08-25",
        status: "pending",
        planRequested: "ADVANCED",
        studentCount: 210,
        details: "New Advanced subscription.",
      }),
      req({
        id: "pr-h13-2",
        type: "module_add_remove",
        requestedBy: "Arun Menon",
        submittedOn: "2026-08-26",
        status: "pending",
        modules: ["LAUNDRY"],
        details: "Also requested Laundry add-on (Elite module).",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h13-1",
        invoiceNo: "yoco/inv/2026-27/0006",
        billingPeriodStart: "2026-09-15",
        billingPeriodEnd: "2027-09-14",
        students: 210,
        amount: 151200,
        gst: 27216,
        total: 178416,
        status: "unpaid",
        dateGenerated: "2026-08-25",
        sameState: false,
        dueDate: "2026-09-20",
        modules: [...DEFAULT_PLAN_MODULES.ADVANCED],
        plan: "ADVANCED",
        rate: 60,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h13-2", "Module add request submitted — Laundry", "2026-08-26T11:00:00", "Arun Menon"),
      ev("a-h13-1", "New subscription submitted — Advanced", "2026-08-25T10:00:00", "Arun Menon"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h14",
    hostelCode: "YS-CHD-002",
    name: "Cedar House",
    city: "Chandigarh",
    state: "Chandigarh",
    adminName: "Harpreet Kaur",
    adminPhone: "+91 98150 99887",
    plan: "ELITE",
    status: "expired",
    billingCycle: "ANNUAL",
    studentCount: 60,
    subscriptionStartDate: "2026-04-01",
    renewalDate: "2027-04-01",
    lastPaymentDate: "2026-04-02",
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.ELITE],
    pendingRequests: [],
    invoices: [
      inv({
        id: "inv-h14-1",
        invoiceNo: "yoco/inv/2025-26/0008",
        billingPeriodStart: "2026-04-01",
        billingPeriodEnd: "2027-03-31",
        students: 60,
        amount: 50400,
        gst: 9072,
        total: 59472,
        status: "voided",
        dateGenerated: "2026-03-25",
        sameState: false,
        dueDate: "2026-04-10",
        modules: [...DEFAULT_PLAN_MODULES.ELITE],
        plan: "ELITE",
        rate: 70,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h14-2", "Subscription voided — duplicate onboarding", "2026-05-12T16:00:00"),
      ev("a-h14-1", "Elite plan activated", "2026-04-01T09:00:00"),
    ],
    notes: [],
  }),
  hostel({
    hostelId: "h15",
    hostelCode: "YS-NAG-016",
    name: "Ivy League Hostel",
    city: "Nagpur",
    state: "Maharashtra",
    adminName: "Pooja Bhagat",
    adminPhone: "+91 98222 55661",
    plan: "PREMIUM",
    status: "expired",
    billingCycle: "ANNUAL",
    studentCount: 40,
    subscriptionStartDate: "2026-07-01",
    renewalDate: "2026-07-31",
    trialLapsed: true,
    modulesLocked: true,
    activeModules: [...DEFAULT_PLAN_MODULES.PREMIUM],
    pendingRequests: [
      req({
        id: "pr-h15-1",
        type: "renewal_after_expiry",
        requestedBy: "Pooja Bhagat",
        submittedOn: "2026-08-20",
        status: "pending",
        planRequested: "PREMIUM",
        studentCount: 40,
        details: "Trial ended — wants to convert to paid Premium.",
      }),
    ],
    invoices: [
      inv({
        id: "inv-h15-1",
        invoiceNo: "yoco/inv/2026-27/0002",
        billingPeriodStart: "2026-07-01",
        billingPeriodEnd: "2026-07-31",
        students: 40,
        amount: 0,
        gst: 0,
        total: 0,
        status: "unpaid",
        dateGenerated: "2026-07-01",
        sameState: true,
        dueDate: "2026-07-31",
        modules: [...DEFAULT_PLAN_MODULES.PREMIUM],
        plan: "PREMIUM",
        rate: 0,
      }),
    ],
    paymentProofs: [],
    auditTrail: [
      ev("a-h15-2", "Trial ended — subscription expired", "2026-08-01T00:05:00", "System"),
      ev("a-h15-1", "Trial started", "2026-07-01T09:00:00"),
    ],
    notes: [
      note("n-h15-1", "Did not convert after trial. Follow up to start a paid plan.", "2026-08-05T10:00:00"),
    ],
  }),
]

export const ARR_TREND = [
  { month: "2025-09", arr: 980000, label: "Sep 2025" },
  { month: "2025-10", arr: 1040000, label: "Oct 2025" },
  { month: "2025-11", arr: 1180000, label: "Nov 2025" },
  { month: "2025-12", arr: 1210000, label: "Dec 2025" },
  { month: "2026-01", arr: 1290000, label: "Jan 2026" },
  { month: "2026-02", arr: 1315000, label: "Feb 2026" },
  { month: "2026-03", arr: 1280000, label: "Mar 2026" },
  { month: "2026-04", arr: 1340000, label: "Apr 2026" },
  { month: "2026-05", arr: 1390000, label: "May 2026" },
  { month: "2026-06", arr: 1460000, label: "Jun 2026" },
  { month: "2026-07", arr: 1410000, label: "Jul 2026" },
  { month: "2026-08", arr: 1520000, label: "Aug 2026" },
]

export const CHURN_TREND = [
  { month: "Sep 2025", rate: 2.1 },
  { month: "Oct 2025", rate: 1.8 },
  { month: "Nov 2025", rate: 2.4 },
  { month: "Dec 2025", rate: 3.1 },
  { month: "Jan 2026", rate: 2.6 },
  { month: "Feb 2026", rate: 1.9 },
  { month: "Mar 2026", rate: 2.8 },
  { month: "Apr 2026", rate: 2.2 },
  { month: "May 2026", rate: 1.6 },
  { month: "Jun 2026", rate: 2.0 },
  { month: "Jul 2026", rate: 3.4 },
  { month: "Aug 2026", rate: 2.7 },
]

export const SIGNUPS_BY_MONTH = [
  { month: "Sep", count: 1 },
  { month: "Oct", count: 2 },
  { month: "Nov", count: 1 },
  { month: "Dec", count: 0 },
  { month: "Jan", count: 3 },
  { month: "Feb", count: 1 },
  { month: "Mar", count: 0 },
  { month: "Apr", count: 2 },
  { month: "May", count: 1 },
  { month: "Jun", count: 2 },
  { month: "Jul", count: 2 },
  { month: "Aug", count: 3 },
]

export const UNOCCUPIED_HOSTELS = [
  { hostelId: "h16", hostelCode: "YS-PUN-099", name: "Lotus Boys Hostel", city: "Pune", state: "Maharashtra", adminName: "Nitin Kale", adminPhone: "+91 98900 11122" },
  { hostelId: "h17", hostelCode: "YS-BLR-088", name: "Petal Girls Hostel", city: "Bengaluru", state: "Karnataka", adminName: "Divya Shetty", adminPhone: "+91 99000 33445" },
]
